### ISSUE TITLE
Hello! Kainuma!

### ISSUE THREAD

**Issue by akimasa-l** [mpses/entrance_system#1]
Hello! Kainuma!

I'm the head of 62nd Seiko Festa Initialization Department(unofficial), Akimasa_L.

You seem to create some repositories about the projects of 62nd Seiko Festa. But I hate it that every project is under a person @mpses. You had better think about creating a new **Organization**.

I will show you how to create a new organization.

1. Click your icon and go to settings.

1. You can find Organization tab.

1. Make a organization like this:
![image](https://user-images.githubusercontent.com/62997105/126025562-90ba2e3f-6f40-4925-84de-d1e6dea2a8b5.png)

1. If you want to know further about organization, you can check the in [GitHub's official docs][make_a_organization]

Thank you for reading, and have a nice GitHub life!

[make_a_organization]:https://docs.github.com/ja/organizations/collaborating-with-groups-in-organizations/creating-a-new-organization-from-scratch

**Comment by mpses** [comment]
Hi @akimasa-l, thanks for opening the issue. I suppose that is absolutely right, however, what should the name of the organization be? It can be "seiko-student-council", "seiko-festa-62nd" or "seiko-festa-technology-department".

**Comment by akimasa-l** [comment]
nandemo iiyo
